baseURL = 'https://markhartzheimart.netlify.app'
languageCode = 'en-us'
title = 'Artist Gallery - Demo'
# theme = 'ananke'  # Removed to avoid template conflicts
buildFuture = true

[taxonomies]
  series = "series"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Artist Gallery"
    params = { flag = "ðŸ‡¬ðŸ‡§" }
    
  [languages.de]
    languageName = "Deutsch"
    weight = 2
    title = "KÃ¼nstler Galerie"
    params = { flag = "ðŸ‡©ðŸ‡ª" }

[params]
  featured_image = '/images/hero.jpg'
  description = "Art Gallery Demo"
  favicon = "/favicon.ico"

# Menu configuration
[[languages.en.menu.main]]
  name = "HOME"
  url = "/"
  weight = 0

[[languages.en.menu.main]]
  name = "SERIES"
  url = "/series/"
  weight = 1

[[languages.en.menu.main]]
  name = "ABOUT"
  url = "/about/"
  weight = 2

[[languages.en.menu.main]]
  name = "LATEST NEWS"
  url = "/latest/"
  weight = 3


# German menu
[[languages.de.menu.main]]
  name = "HOME"
  url = "/de/"
  weight = 0

[[languages.de.menu.main]]
  name = "SERIEN"
  url = "/de/series/"
  weight = 1

[[languages.de.menu.main]]
  name = "ÃœBER"
  url = "/de/about/"
  weight = 2

[[languages.de.menu.main]]
  name = "NEUESTE"
  url = "/de/latest/"
  weight = 3
